apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-operator-work
rules:
  - apiGroups: ['helm.fluxcd.io']
    resources: ['helmreleases']
    verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
